CREATE SEQUENCE IF NOT EXISTS USUARIOS_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS RECURSOS_ID_SEQ;

CREATE TABLE IF NOT EXISTS ROLES (
  id INT NOT NULL,
  nombre VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (id))
;

CREATE TABLE IF NOT EXISTS USUARIOS (
  id INT NOT NULL DEFAULT nextval('USUARIOS_ID_SEQ'),
  nombre VARCHAR(45) NOT NULL UNIQUE,
  contrasena VARCHAR(20) NOT NULL,
  programa VARCHAR(30) NOT NULL,
  rol INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(rol) REFERENCES ROLES(id))
;

CREATE TABLE IF NOT EXISTS RECURSOS (
  id INT NOT NULL DEFAULT nextval('RECURSOS_ID_SEQ'),
  nombre VARCHAR(45) NOT NULL UNIQUE,
  tipo CHAR(1) NOT NULL,
  capacidad INT NOT NULL,
  ubicacion VARCHAR(20) NOT NULL,
  estado BOOLEAN NOT NULL,
  PRIMARY KEY (id))
;

insert into ROLES (ID,nombre) VALUES ( 1,'Administrador');
insert into ROLES (ID,nombre) VALUES ( 2,'Comunidad');