CREATE SEQUENCE IF NOT EXISTS USUARIOS_ID_SEQ;

CREATE TABLE IF NOT EXISTS ROLES (
  id INT NOT NULL,
  nombre VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (id))
;

CREATE TABLE IF NOT EXISTS USUARIOS (
  id INT NOT NULL DEFAULT nextval('USUARIOS_ID_SEQ'),
  nombre VARCHAR(45) NOT NULL UNIQUE,
  contrasena VARCHAR(20) NOT NULL,
  programa VARCHAR(30) NOT NULL,
  rol INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY(rol) REFERENCES ROLES(id))
;



insert into ROLES (ID,nombre) VALUES ( 1,'Administrador');
insert into ROLES (ID,nombre) VALUES ( 2,'Comunidad');